plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
include:
  - README.md
  - LICENSE.md
title: MOSAICC
markdown: GFM
show_downloads: false
theme:  jekyll-theme-architect


# jekyll-theme-minimal     <-- blue
# jekyll-theme-hacker      <-- black background with typewriter font
# jekyll-theme-architect   <-- handwriting-like font
# jekyll-theme-merlot      <-- scrolls as decorations
# jekyll-theme-cayman      <-- green/blue top banner 
# jekyll-theme-midnight    <-- dark
#
# others:                  <-- https://github.com/pages-themes
